import React, { createContext, useContext, useState } from 'react';

export const DataContext = createContext();

export const courseCatalog = [
  // Humanities
  { id: "WR1000", fullName: "Basic Writing Skills", difficulty: "Beginner", availableTerms: ["A", "B", "C"], department: "Humanities" },
  { id: "WR1101", fullName: "Introduction to Writing", difficulty: "Beginner", availableTerms: ["A", "B", "D"], department: "Humanities" },
  { id: "WR1102", fullName: "Introduction to Literature", difficulty: "Beginner", availableTerms: ["A", "B", "C"], department: "Humanities" },
  { id: "WR2014", fullName: "World Literature", difficulty: "Intermediate", availableTerms: ["A", "B"], department: "Humanities" },
  { id: "WR2301", fullName: "Creative Writing Workshop", difficulty: "Beginner", availableTerms: ["A", "B", "C"], department: "Humanities" },
  { id: "WR2467", fullName: "Modern Poetry", difficulty: "Beginner", availableTerms: ["A", "B", "D"], department: "Humanities" },
  { id: "WR2914", fullName: "Shakespearean Studies", difficulty: "Intermediate", availableTerms: ["A", "D"], department: "Humanities" },
  { id: "WR3120", fullName: "The Art of Fiction", difficulty: "Intermediate", availableTerms: ["A", "C"], department: "Humanities" },
  { id: "WR3367", fullName: "Advanced Writing Seminar", difficulty: "Intermediate", availableTerms: ["A", "B", "D"], department: "Humanities" },
  { id: "WR3505", fullName: "Literary Criticism", difficulty: "Intermediate", availableTerms: ["A", "C"], department: "Humanities" },
  { id: "WR3769", fullName: "Drama and Performance", difficulty: "Advanced", availableTerms: ["B", "D"], department: "Humanities" },
  { id: "WR4012", fullName: "Screenwriting", difficulty: "Intermediate", availableTerms: ["A", "B", "C"], department: "Humanities" },
  { id: "WR4217", fullName: "The Short Story", difficulty: "Advanced", availableTerms: ["A", "C"], department: "Humanities" },
  { id: "WR4550", fullName: "Romantic Literature", difficulty: "Intermediate", availableTerms: ["B", "C"], department: "Humanities" },
  { id: "WR4822", fullName: "American Poetry", difficulty: "Intermediate", availableTerms: ["B", "D"], department: "Humanities" },
  { id: "WR4975", fullName: "Postcolonial Literature", difficulty: "Advanced", availableTerms: ["C", "D"], department: "Humanities" },
  { id: "WR5100", fullName: "Creative Nonfiction", difficulty: "Advanced", availableTerms: ["B", "C"], department: "Humanities" },

  // Environment
  { id: "ENV1053", fullName: "Intro to Environmental Science", difficulty: "Beginner", availableTerms: ["A", "B", "C"], department: "Environment" },
  { id: "ENV1938", fullName: "Environmental Ethics", difficulty: "Beginner", availableTerms: ["A", "B", "C", "D"], department: "Environment" },
  { id: "ENV2139", fullName: "Environmental Policy", difficulty: "Intermediate", availableTerms: ["A", "B", "D"], department: "Environment" },
  { id: "ENV2981", fullName: "Renewable Energy Systems", difficulty: "Beginner", availableTerms: ["A", "B"], department: "Environment" },
  { id: "ENV3702", fullName: "Climate Change and Sustainability", difficulty: "Advanced", availableTerms: ["A", "C"], department: "Environment" },
  
  // Computer Science
  { id: "CS1001", fullName: "Introduction to Programming", difficulty: "Beginner", availableTerms: ["A", "B"], department: "Computer Science" },
  { id: "CS1123", fullName: "Introduction to Computer Science", difficulty: "Beginner", availableTerms: ["A", "B"], department: "Computer Science" },
  { id: "CS1350", fullName: "Discrete Mathematics", difficulty: "Intermediate", availableTerms: ["A", "C", "D"], department: "Computer Science" },
  { id: "CS1465", fullName: "Computer Networks", difficulty: "Intermediate", availableTerms: ["A", "B", "D"], department: "Computer Science" },
  { id: "CS2001", fullName: "Operating Systems", difficulty: "Intermediate", availableTerms: ["A", "B", "C"], department: "Computer Science" },
  { id: "CS2245", fullName: "Data Structures and Algorithms", difficulty: "Intermediate", availableTerms: ["A", "B", "C"], department: "Computer Science" },
  { id: "CS2500", fullName: "Theory of Computation", difficulty: "Intermediate", availableTerms: ["A", "B", "D"], department: "Computer Science" },
  { id: "CS2674", fullName: "Database Systems", difficulty: "Intermediate", availableTerms: ["A", "B"], department: "Computer Science" },
  { id: "CS3001", fullName: "Software Development", difficulty: "Intermediate", availableTerms: ["A", "C", "D"], department: "Computer Science" },
  { id: "CS3041", fullName: "Human-Computer Interactions", difficulty: "Intermediate", availableTerms: ["A", "C", "D"], department: "Computer Science" },
  { id: "CS3120", fullName: "Web Development", difficulty: "Intermediate", availableTerms: ["A", "B", "C", "D"], department: "Computer Science" },
  { id: "CS3350", fullName: "Computer Graphics", difficulty: "Intermediate", availableTerms: ["A", "C", "D"], department: "Computer Science" },
  { id: "CS3557", fullName: "Software Engineering", difficulty: "Advanced", availableTerms: ["B", "C", "D"], department: "Computer Science" },
  { id: "CS3701", fullName: "Machine Learning", difficulty: "Advanced", availableTerms: ["A", "B", "C"], department: "Computer Science" },
  { id: "CS3999", fullName: "Cybersecurity", difficulty: "Advanced", availableTerms: ["B", "C"], department: "Computer Science" },
  { id: "CS4120", fullName: "Distributed Systems", difficulty: "Advanced", availableTerms: ["A", "C"], department: "Computer Science" },
  { id: "CS4501", fullName: "Parallel Computing", difficulty: "Advanced", availableTerms: ["B", "C", "D"], department: "Computer Science" },
  { id: "CS4800", fullName: "Artificial Intelligence", difficulty: "Advanced", availableTerms: ["A", "C", "D"], department: "Computer Science" },
  { id: "CS4999", fullName: "Cloud Computing", difficulty: "Advanced", availableTerms: ["B", "C"], department: "Computer Science" },
  { id: "CS5200", fullName: "Mobile App Development", difficulty: "Advanced", availableTerms: ["A", "C"], department: "Computer Science" },
  { id: "CS5502", fullName: "Big Data Analytics", difficulty: "Advanced", availableTerms: ["B", "C"], department: "Computer Science" }, 
  
  // Mathematics
  { id: "MA1010", fullName: "Calculus I", difficulty: "Beginner", availableTerms: ["A", "B", "C", "D"], department: "Mathematics" },
  { id: "MA1020", fullName: "Introduction to Algebra", difficulty: "Beginner", availableTerms: ["A", "B", "C", "D"], department: "Mathematics" },
  { id: "MA1030", fullName: "Elementary Geometry", difficulty: "Beginner", availableTerms: ["A", "B"], department: "Mathematics" },
  { id: "MA1040", fullName: "Basic Statistics", difficulty: "Beginner", availableTerms: ["A", "B", "C"], department: "Mathematics" },
  { id: "MA1050", fullName: "Introduction to Trigonometry", difficulty: "Beginner", availableTerms: ["A", "B", "C", "D"], department: "Mathematics" },
  { id: "MA1070", fullName: "Mathematical Foundations", difficulty: "Beginner", availableTerms: ["A", "B", "C"], department: "Mathematics" },
  { id: "MA1080", fullName: "Introduction to Calculus", difficulty: "Beginner", availableTerms: ["A", "B", "C", "D"], department: "Mathematics" },
  { id: "MA1349", fullName: "PreCalculus", difficulty: "Beginner", availableTerms: ["A", "B", "C", "D"], department: "Mathematics" },
  { id: "MA2015", fullName: "Calculus II", difficulty: "Beginner", availableTerms: ["A", "B", "C"], department: "Mathematics" },
  { id: "MA2017", fullName: "Mathematical Physics", difficulty: "Advanced", availableTerms: ["B", "C", "D"], department: "Mathematics" },
  { id: "MA2386", fullName: "Advanced Calculus", difficulty: "Intermediate", availableTerms: ["B", "C", "D"], department: "Mathematics" },
  { id: "MA2723", fullName: "Linear Algebra", difficulty: "Intermediate", availableTerms: ["A", "B", "C"], department: "Mathematics" },
  { id: "MA2860", fullName: "Discrete Mathematics", difficulty: "Intermediate", availableTerms: ["A", "B", "C", "D"], department: "Mathematics" },
  { id: "MA3022", fullName: "Mathematical Analysis", difficulty: "Advanced", availableTerms: ["B", "C", "D"], department: "Mathematics" },
  { id: "MA3131", fullName: "Probability Theory", difficulty: "Intermediate", availableTerms: ["A", "B", "C"], department: "Mathematics" },
  { id: "MA3213", fullName: "Quantum Mechanics", difficulty: "Intermediate", availableTerms: ["B", "C", "D"], department: "Mathematics" },
  { id: "MA3245", fullName: "Abstract Algebra", difficulty: "Intermediate", availableTerms: ["A", "B", "C"], department: "Mathematics" },
  { id: "MA3546", fullName: "Real Analysis", difficulty: "Advanced", availableTerms: ["A", "B", "C"], department: "Mathematics" },
  { id: "MA3789", fullName: "Numerical Analysis", difficulty: "Intermediate", availableTerms: ["A", "C", "D"], department: "Mathematics" },
  { id: "MA3915", fullName: "Differential Geometry", difficulty: "Advanced", availableTerms: ["B", "C", "D"], department: "Mathematics" },
  { id: "MA4007", fullName: "Graph Theory", difficulty: "Intermediate", availableTerms: ["B", "C"], department: "Mathematics" },
  { id: "MA4034", fullName: "Differential Equations", difficulty: "Intermediate", availableTerms: ["A", "D"], department: "Mathematics" },
  { id: "MA4102", fullName: "Mathematical Modeling II", difficulty: "Advanced", availableTerms: ["B", "C", "D"], department: "Mathematics" },
  { id: "MA4508", fullName: "Advanced Topics in Mathematics", difficulty: "Intermediate", availableTerms: ["B"], department: "Mathematics" },
  { id: "MA4523", fullName: "Mathematical Logic", difficulty: "Advanced", availableTerms: ["D"], department: "Mathematics" },
  { id: "MA4888", fullName: "Mathematical Modeling", difficulty: "Advanced", availableTerms: ["A","C"], department: "Mathematics" },

  // Biology
  { id: "BB1001", fullName: "Introduction to Biology", difficulty: "Beginner", availableTerms: ["A", "B"], department: "Biology" },
  { id: "BB1467", fullName: "Botany Fundamentals", difficulty: "Intermediate", availableTerms: ["A", "C", "D"], department: "Biology" },
  { id: "BB2001", fullName: "Genetics", difficulty: "Intermediate", availableTerms: ["A", "B", "C"], department: "Biology" },
  { id: "BB2467", fullName: "Microbiology", difficulty: "Advanced", availableTerms: ["B", "C", "D"], department: "Biology" },
  { id: "BB3001", fullName: "Cell Biology", difficulty: "Advanced", availableTerms: ["A", "B", "D"], department: "Biology" },
  { id: "BB3505", fullName: "Neuroscience", difficulty: "Advanced", availableTerms: ["A", "C"], department: "Biology" },
  { id: "BB4001", fullName: "Ecology", difficulty: "Advanced", availableTerms: ["A", "B", "C"], department: "Biology" },
  { id: "BB4500", fullName: "Evolutionary Biology", difficulty: "Advanced", availableTerms: ["A", "B", "C", "D"], department: "Biology" },
  { id: "BB4712", fullName: "Molecular Ecology", difficulty: "Advanced", availableTerms: ["A", "C", "D"], department: "Biology" },
  { id: "BB4762", fullName: "Marine Biology", difficulty: "Advanced", availableTerms: ["A", "C"], department: "Biology" },
  { id: "BB4798", fullName: "Plant Physiology", difficulty: "Advanced", availableTerms: ["B", "D"], department: "Biology" },
  { id: "BB4803", fullName: "Biotechnology", difficulty: "Advanced", availableTerms: ["A", "D"], department: "Biology" },
  { id: "BB4805", fullName: "Cancer Biology", difficulty: "Advanced", availableTerms: ["B", "C", "D"], department: "Biology" },
  { id: "BB4821", fullName: "Systems Biology", difficulty: "Advanced", availableTerms: ["B", "C"], department: "Biology" },
  { id: "BB4859", fullName: "Genomics", difficulty: "Advanced", availableTerms: ["B", "D"], department: "Biology" },
  { id: "BB4867", fullName: "Developmental Biology", difficulty: "Advanced", availableTerms: ["A", "C", "D"], department: "Biology" },
  { id: "BB4874", fullName: "Biophysics", difficulty: "Advanced", availableTerms: ["A", "C"], department: "Biology" },
  { id: "BB4885", fullName: "Biochemistry", difficulty: "Advanced", availableTerms: ["B", "D"], department: "Biology" },
  { id: "BB4886", fullName: "Immunology", difficulty: "Advanced", availableTerms: ["A", "C", "D"], department: "Biology" },
  { id: "BB4729", fullName: "Bioinformatics", difficulty: "Advanced", availableTerms: ["B", "C"], department: "Biology" },
  
  // Chemistry
  { id: "CH1010", fullName: "General Chemistry", difficulty: "Beginner", availableTerms: ["A", "B", "C", "D"], department: "Chemistry" },
  { id: "CH1467", fullName: "Analytical Chemistry", difficulty: "Intermediate", availableTerms: ["A", "C", "D"], department: "Chemistry" },
  { id: "CH2001", fullName: "Inorganic Chemistry", difficulty: "Intermediate", availableTerms: ["A", "B", "C"], department: "Chemistry" },
  { id: "CH2467", fullName: "Physical Chemistry", difficulty: "Advanced", availableTerms: ["B", "C", "D"], department: "Chemistry" },
  { id: "CH3001", fullName: "Organic Synthesis", difficulty: "Advanced", availableTerms: ["A", "C", "D"], department: "Chemistry" },
  { id: "CH3505", fullName: "Biochemistry", difficulty: "Advanced", availableTerms: ["A", "B", "D"], department: "Chemistry" },
  { id: "CH4001", fullName: "Polymer Chemistry", difficulty: "Advanced", availableTerms: ["B", "C"], department: "Chemistry" },
  { id: "CH4500", fullName: "Nanotechnology", difficulty: "Advanced", availableTerms: ["A", "B", "C", "D"], department: "Chemistry" },
  { id: "CH5001", fullName: "Environmental Chemistry", difficulty: "Advanced", availableTerms: ["B", "D"], department: "Chemistry" },
  { id: "CH5502", fullName: "Medicinal Chemistry", difficulty: "Advanced", availableTerms: ["A", "C"], department: "Chemistry" },
  { id: "CH6001", fullName: "Surface Chemistry", difficulty: "Advanced", availableTerms: ["B", "C", "D"], department: "Chemistry" },
  { id: "CH6500", fullName: "Chemical Kinetics", difficulty: "Advanced", availableTerms: ["A", "D"], department: "Chemistry" },
  { id: "CH7002", fullName: "Spectroscopy", difficulty: "Advanced", availableTerms: ["B", "C"], department: "Chemistry" },
  { id: "CH7501", fullName: "Computational Chemistry", difficulty: "Advanced", availableTerms: ["A", "C", "D"], department: "Chemistry" },
  { id: "CH8000", fullName: "Coordination Chemistry", difficulty: "Advanced", availableTerms: ["B", "D"], department: "Chemistry" },
  { id: "CH8500", fullName: "Industrial Chemistry", difficulty: "Advanced", availableTerms: ["A", "C"], department: "Chemistry" },
  { id: "CH9001", fullName: "Supramolecular Chemistry", difficulty: "Advanced", availableTerms: ["B", "D"], department: "Chemistry" },
  { id: "CH9502", fullName: "Solid State Chemistry", difficulty: "Advanced", availableTerms: ["A", "C", "D"], department: "Chemistry" },
  { id: "CH9801", fullName: "Electrochemistry", difficulty: "Advanced", availableTerms: ["B", "C"], department: "Chemistry" },
  { id: "CH9880", fullName: "Chemical Engineering", difficulty: "Advanced", availableTerms: ["A", "D"], department: "Chemistry" },
  
  // Physics
  { id: "PH1001", fullName: "Physics Fundamentals", difficulty: "Beginner", availableTerms: ["A", "B", "C"], department: "Physics" },
  { id: "PH1467", fullName: "Thermodynamics", difficulty: "Intermediate", availableTerms: ["A", "C", "D"], department: "Physics" },
  { id: "PH2001", fullName: "Quantum Mechanics", difficulty: "Intermediate", availableTerms: ["A", "B", "C"], department: "Physics" },
  { id: "PH2467", fullName: "Particle Physics", difficulty: "Advanced", availableTerms: ["B", "C", "D"], department: "Physics" },
  { id: "PH3001", fullName: "Electronics", difficulty: "Advanced", availableTerms: ["A", "C", "D"], department: "Physics" },
  { id: "PH3505", fullName: "Optics", difficulty: "Advanced", availableTerms: ["A", "B", "D"], department: "Physics" },
  { id: "PH4001", fullName: "Astrophysics", difficulty: "Advanced", availableTerms: ["B", "C"], department: "Physics" },
  { id: "PH4500", fullName: "Nuclear Physics", difficulty: "Advanced", availableTerms: ["A", "C", "D"], department: "Physics" },
  { id: "PH5001", fullName: "Condensed Matter Physics", difficulty: "Advanced", availableTerms: ["B", "D"], department: "Physics" },
  { id: "PH5502", fullName: "Plasma Physics", difficulty: "Advanced", availableTerms: ["A", "C"], department: "Physics" },
  { id: "PH6001", fullName: "High Energy Physics", difficulty: "Advanced", availableTerms: ["B", "C", "D"], department: "Physics" },
  { id: "PH6500", fullName: "Atomic Physics", difficulty: "Advanced", availableTerms: ["A", "D"], department: "Physics" },
  { id: "PH7002", fullName: "Solid State Physics", difficulty: "Advanced", availableTerms: ["B", "C"], department: "Physics" },
  { id: "PH7501", fullName: "Cosmology", difficulty: "Advanced", availableTerms: ["A", "C", "D"], department: "Physics" },
  { id: "PH8000", fullName: "Fluid Dynamics", difficulty: "Advanced", availableTerms: ["B", "D"], department: "Physics" },
  { id: "PH8500", fullName: "Acoustics", difficulty: "Advanced", availableTerms: ["A", "C"], department: "Physics" },
  { id: "PH9001", fullName: "Gravitation", difficulty: "Advanced", availableTerms: ["B", "D"], department: "Physics" },
  { id: "PH9502", fullName: "Magnetism", difficulty: "Advanced", availableTerms: ["A", "C", "D"], department: "Physics" },
  { id: "PH9801", fullName: "Chaos Theory", difficulty: "Advanced", availableTerms: ["B", "C"], department: "Physics" },
  { id: "PH9880", fullName: "Biophysics", difficulty: "Advanced", availableTerms: ["A"], department: "Physics" },
  
  // Biomedical Engineering
  { id: "BME1001", fullName: "Intro to BME", difficulty: "Intermediate", availableTerms: ["A", "B", "C", "D"], department: "Biomedical Engineering" },
  { id: "BME2001", fullName: "Biomaterials", difficulty: "Advanced", availableTerms: ["A", "B"], department: "Biomedical Engineering" },
  { id: "BME2210", fullName: "Bioinstrumentation", difficulty: "Beginner", availableTerms: ["A", "B", "C"], department: "Biomedical Engineering" },
  { id: "BME2211", fullName: "Data Analysis in Biomedical Engineering", difficulty: "Intermediate", availableTerms: ["A", "B", "D"], department: "Biomedical Engineering" },
  { id: "BME2502", fullName: "Biomechanics", difficulty: "Advanced", availableTerms: ["A", "B", "D"], department: "Biomedical Engineering" },
  { id: "BME3610", fullName: "Biotransport Analysis", difficulty: "Intermediate", availableTerms: ["A", "C"], department: "Biomedical Engineering" },
  { id: "BME4828", fullName: "Tissue Interactions", difficulty: "Advanced", availableTerms: ["B", "D"], department: "Biomedical Engineering" },

  // Business
  { id: "BUS1001", fullName: "Intro to Business", difficulty: "Intermediate", availableTerms: ["A", "B", "C", "D"], department: "Business" },
  { id: "BUS2020", fullName: "Marketing Fundamentals", difficulty: "Intermediate", availableTerms: ["A", "B", "C"], department: "Business" },
  { id: "BUS2080", fullName: "Business Writing", difficulty: "Advanced", availableTerms: ["B", "D"], department: "Business" },
  { id: "BUS2001", fullName: "Business Decisions", difficulty: "Beginner", availableTerms: ["A", "B", "C", "D"], department: "Business" },
  { id: "BUS3001", fullName: "Advanced Business Strategy", difficulty: "Advanced", availableTerms: ["A", "D"], department: "Business" },
  { id: "BUS3050", fullName: "Managerial Accounting", difficulty: "Intermediate", availableTerms: ["A", "B"], department: "Business" },
  { id: "BUS4001", fullName: "Entrepreneurship and Innovation", difficulty: "Intermediate", availableTerms: ["A", "B", "D"], department: "Business" },
];

  export const DataProvider = ({ children }) => {
    const [studentSchedule, setStudentSchedule] = useState([
      { year: 1, term: "A", courseId: "CS1001" },
      { year: 1, term: "A", courseId: "MA1010" },
      { year: 1, term: "A", courseId: "WR1000" },
      { year: 1, term: "B", courseId: "CS1123" },
      { year: 1, term: "B", courseId: "WR1101" },
      { year: 1, term: "B", courseId: "MA1050" },
      { year: 1, term: "C", courseId: "CS1234" },
      { year: 1, term: "C", courseId: "WR1102" },
      { year: 1, term: "C", courseId: "BB1467" },
      { year: 1, term: "D", courseId: "CS3350" },
      { year: 1, term: "D", courseId: "CS2500" },
      { year: 1, term: "D", courseId: "MA1020" },
    
      { year: 2, term: "A", courseId: "CS1350" },
      { year: 2, term: "A", courseId: "CS1010" },
      { year: 2, term: "A", courseId: "WR2014" },
      { year: 2, term: "B", courseId: "CS1465" },
      { year: 2, term: "B", courseId: "BUS1001" },
      { year: 2, term: "B", courseId: "MA4001" },
      { year: 2, term: "C", courseId: "CS2001" },
      { year: 2, term: "C", courseId: "MA1349" },
      { year: 2, term: "C", courseId: "WR2301" },
      { year: 2, term: "D", courseId: "CS3041" },
      { year: 2, term: "D", courseId: "MA3789" },
      { year: 2, term: "D", courseId: "BME4828" },

      { year: 3, term: "A", courseId: "WR2914" },
      { year: 3, term: "A", courseId: "MA3001" },
      { year: 3, term: "A", courseId: "WR3120" },
      { year: 3, term: "B", courseId: "CS2674" },
      { year: 3, term: "B", courseId: "MA3022" },
      { year: 3, term: "B", courseId: "BME2210" },
      { year: 3, term: "C", courseId: "CS3001" },
      { year: 3, term: "C", courseId: "MA3245" },
      { year: 3, term: "C", courseId: "CS5200" },
      { year: 3, term: "D", courseId: "CS3120" },
      { year: 3, term: "D", courseId: "BUS2001" },
      { year: 3, term: "D", courseId: "BME2211" },
    
      { year: 4, term: "A", courseId: "CS3701" },
      { year: 4, term: "A", courseId: "BUS2020" },
      { year: 4, term: "A", courseId: "BB4500" },
      { year: 4, term: "B", courseId: "CS4999" },
      { year: 4, term: "B", courseId: "MA4102" },
      { year: 4, term: "B", courseId: "CH2467" },
      { year: 4, term: "C", courseId: "CS4120" },
      { year: 4, term: "C", courseId: "MA4007" },
      { year: 4, term: "C", courseId: "CS5502" },
      { year: 4, term: "D", courseId: "CS4501" },
      { year: 4, term: "D", courseId: "MA5100" },
      { year: 4, term: "D", courseId: "CS3557" },
    ]);
      

 return (
    <DataContext.Provider value={{ courseCatalog, studentSchedule, setStudentSchedule }}>
      {children}
    </DataContext.Provider>
  );
};

export const useDataContext = () => useContext(DataContext);